unique_ids:
  assets:
    standard-page.html: TL55776JXNQAOA2VYVXVIIGHH34MJYIF
    theme.css: GXI27KZARXI7H7PVK5UE6E65VK7TAQD3
  forms:
    ForgottenPasswordDialog: KSTGVWGPPWCGERPTMTE3RETPAOU6BKGL
    LoginDialog: SNIRK642KXCITZMEXANLSPVTUZ2CAPAD
    PasswordResetDialog: 3TOQQ72FB3K3Y6QLJEWXYTOHQKWGXEUD
    SignupDialog: LL6NBOH5UT7PK6E67VDX5APMSZXJLD3I
    Test: NYVKBCZOW46KMETRMWY6UQ3P47RC3COV
  modules:
    Module1: LV4LHNBRYDLHEN72OFXF5YWQ52BZGSXF
    login_flow: USMN5RAASF6YBZZJPNXGW2AJBSKX34N4
  scripts: {}
  server_modules:
    ServerModule1: 6IYGP6UDQ4VORS3F7WJBBN27V4ZWPRY6
